### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by clazarr** [pauldeen79/TemplateFramework#35]
This project appears to be referenced from some [Microsoft.TestPlatform](https://www.nuget.org/packages/Microsoft.TestPlatform/17.7.2) assemblies, which are typically pulled in to test projects. I'm not sure how or why it is referenced from those as I'm merely a consumer of the higher-level Microsoft.TestPlatform NuGet package in my testing project.

The potential issue this presents is that some SAST/scanning tools, such as [Synopsys Black Duck](https://www.synopsys.com/software-integrity/software-composition-analysis-tools/black-duck-sca.html), may flag components that have an unknown or no license, which is what I'm observing here in this snippet from a Black Duck report covering my test project that cites the  [pauldeen79.TemplateFramework.Console v0.7.3](https://www.nuget.org/packages/pauldeen79.TemplateFramework.Console/0.7.3) component as having an "Unknown License" as an issue:

<img width="767" alt="image" src="https://github.com/pauldeen79/TemplateFramework/assets/26936604/fb686383-47bb-4481-a6a2-99cb3556aaa9">

You may wish to consider adding a license for this repository (for example, MIT) and your NuGet packages to make the licensing clear. Some additional info:
- https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
- https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license
- https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#licensing

**Comment by pauldeen79** [comment]
Agreed that adding a license is better, I will do that.

I'm still not seeing the dependency from Microsoft.TestPlatform or Microsoft.VisualStudio.TestPlatform packages, though...
